apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth
  namespace: auth
spec:
  selector:
    matchLabels:
      app: auth
  replicas: 2
  template:
    metadata:
      labels:
        app: auth
    spec:
      containers:
      - name: auth
        image: nanajanashia/argocd-app:1.1
        ports:
        - containerPort: 8080
